### ISSUE TITLE
Database migrations error when upgrading Ghost

### ISSUE THREAD

**Issue by kashura** [TryGhost/Ghost-CLI#567]
When upgrading from 1.15.1 to 1.18.4 I encountered the following issue that I haven't seen before. I am now getting a 502 Bad Gateway error and even if I rollback I still get a 502. 

```
✔ Checking for latest Ghost version
ℹ Downloading and updating Ghost [skipped]
Running sudo command: systemctl stop ghost_valerakushnir-com
✔ Stopping Ghost
✔ Linking latest Ghost and recording versions
Running sudo command: -E -u ghost /usr/local/lib/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
✖ Running database migrations
An error occurred.
Message: 'Command failed: /bin/sh -c sudo -E -u ghost /usr/local/lib/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
[2017-12-12 16:11:08] ERROR

NAME: MigrationScript
MESSAGE: task.execute is not a function

level:normal

Error occurred while executing the following migration: 1-add-webhooks-table.js
MigrationScript: task.execute is not a function
    at MigrationScript.KnexMigrateError (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/errors.js:7:26)
    at new MigrationScript (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/errors.js:26:26)
    at /usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/index.js:353:19
    at tryCatcher (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

TypeError: task.execute is not a function
    at /usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/index.js:308:25
    at tryCatcher (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)


```

### Debug Information:
* Node Version: v6.11.2
* Ghost-CLI Version: 1.0.3
* Environment: production
* Command: 'ghost update'

**Comment by acburdine** [comment]
@kashura you're running an outdated version of Ghost-CLI. This issue has since been fixed, update your Ghost-CLI version and you won't get this error 😄

**Comment by kashura** [comment]
@acburdine  Thanks for a quick reply. I was able to roll back to Ghost 1.15.1, but I get this error trying to update CLI. I am hitting a wall with Google.

```
root@ghost:/var/www/ghost# ghost --version
Ghost-CLI version: 1.0.3
Ghost Version (at /var/www/ghost): 1.15.1
root@ghost:/var/www/ghost# sudo npm install -g ghost-cli@latest
npm WARN deprecated yarn@1.3.2: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
[     .............] - fetchMetadata: verb afterAdd /root/.npm/wrap-ansi/2.1.0/package/pack[     .............] / fetchMetadata: verb afterAdd /root/.npm/lcid/1.0.0/package/package[     .............] \ fetchMetadata: verb afterAdd /root/.npm/invert-kv/1.0.0/package/pac[     .............] | fetchMetadata: sill mapToRegistry uri https://registry.npmjs.or[     .............] / fetchMetadata: sill mapToRegistry uri https://registry.npmjs./usr/bin/ghost -> /usr/lib/node_modules/ghost-cli/bin/ghost
/usr/lib
└── ghost-cli@1.4.1
```

**Comment by acburdine** [comment]
@kashura it looks like the new CLI version installed fine, based on that output.

**Comment by kashura** [comment]
@acburdine oops, didn't include the version check after trying to update CLI

```
root@ghost:/var/www/ghost# ghost --version
Ghost-CLI version: 1.0.3
Ghost Version (at /var/www/ghost): 1.15.1
```

**Comment by acburdine** [comment]
@kashura so I think I have an idea as to what's going on - but it's hard to remotely debug through a github issue 😉 Would you mind hopping over to ghost's slack channel? (https://slack.ghost.org) -> you can get more immediate help there.

**Comment by d4rkd0s** [comment]
Solution for those that don't want to find it in Slack is:
Ensure you are in the install dir (for Digitalocean its: `/var/www/ghost`)
Then run `sudo npm i -g ghost-cli@latest`
then run `ghost update` or the better `ghost setup` if you need to setup a domain, which is what I needed todo. 🎊
